### ISSUE TITLE
Error when changing the value of extrap_start_time 

### ISSUE THREAD

**Issue by BadourAlBahar** [coxlab/prednet#19]
Traceback (most recent call last):
  File "kitti_train.py", line 59, in <module>
    errors = prednet(inputs)  # errors will be (batch_size, nt, nb_layers)
  File "/home/Badour/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 484, in __call__
    self.build(input_shapes[0])
  File "/home/Badour/prednet/prednet.py", line 223, in build
    self.t_extrap = K.variable(self.extrap_start_time, int)
  File "/home/Badour/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 127, in variable
    v = tf.Variable(value, dtype=_convert_string_dtype(dtype), name=name)
  File "/home/Badour/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 106, in _convert_string_dtype
    raise ValueError('Unsupported dtype:', dtype)
ValueError: ('Unsupported dtype:', <type 'int'>)

I'm using:
Python 2.7
tensorflow 0.12.1 
Keras 1.0.7 
cuDNN 5.1

**Comment by BadourAlBahar** [comment]
How do you change the value of extrap_start_time. If None the code works fine if =5 it does not?

**Comment by tymob** [comment]
me too. I face exactry same problem.

**Comment by ShawnLue** [comment]
It's the variable manipulation problem. Just replace the 'int' with the str, 'int32'.

https://github.com/fchollet/keras/blob/7fc707e13e0e96ef311ab360872f894f664bcfbe/keras/backend/tensorflow_backend.py#L183

**Comment by bill-lotter** [comment]
Thanks @ShawnLue!  This fix is reflected in cc762486

**Comment by kai94** [comment]
I'm getting a different error.
I'm using the last commit #cc76248
Any advice??

`Traceback (most recent call last):
  File "jaxa_evaluate.py", line 45, in <module>   
  test_prednet = PredNet(extrap_start_time = 5, weights=train_model.layers[1].get_weights(), **layer_config)
  TypeError: type object got multiple values for keyword argument 'extrap_start_time'`

**Comment by bill-lotter** [comment]
I would guess that `extrap_start_time` is already in `layer_config`

**Comment by kai94** [comment]
Thanks Bill, it worked now:)
