### ISSUE TITLE
 raise ValueError("Dimension %d must be >= 0" % self._value) ValueError: Dimension  must be >= 0

### ISSUE THREAD

**Issue by wjw1993** [coxlab/prednet#25]
When I was trying to add a new layer to the lowest representation layer, I met this error. I was wondering why I got a negative output dimension after the process of flatening. Here is the source files:

~~~~
import tensorflow as tf
from keras.models import load_model

from keras.models import model_from_json
import os
import numpy as np
np.random.seed(123)
from six.moves import cPickle

from keras import backend as K
from keras.models import Model
from keras.layers import Input, Dense, Flatten
from keras.layers import LSTM
from keras.layers import TimeDistributed
from keras.callbacks import LearningRateScheduler, ModelCheckpoint
from keras.optimizers import Adam

from prednet import PredNet
from data_utils import SequenceGenerator
from kitti_settings import *



nb_epoch = 150
batch_size = 4
samples_per_epoch = 500
N_seq_val = 100  # number of sequences to use for validation


nt=10

MODEL_DATA_DIR='./model_data/'
DATA_DIR='./hkl'

batch_size=10

train_file = os.path.join(DATA_DIR, 'X-Train.hkl')

train_sources = os.path.join(DATA_DIR, 'X-Train-sources.hkl')

val_sources = os.path.join(DATA_DIR, 'X-Val-sources.hkl')

val_file=os.path.join(DATA_DIR, 'X-Val.hkl')

json_file = open(MODEL_DATA_DIR+'prednet_kitti_model.json' , 'r')

loaded_model_json = json_file.read()

json_file.close()


model = model_from_json(loaded_model_json,custom_objects = {'PredNet': PredNet})

model.load_weights(MODEL_DATA_DIR+"prednet_kitti_weights.hdf5")

model.compile(loss='mean_absolute_error', optimizer='adam')


layer_config = model.layers[1].get_config()
layer_config['output_mode'] = 'R0'
dim_ordering = layer_config['dim_ordering']

clf_prednet = PredNet(weights=model.layers[1].get_weights(), **layer_config)

input_shape = list(model.layers[0].batch_input_shape[1:])

input_shape[0] = nt

inputs = Input(shape=tuple(input_shape))

predictions = clf_prednet(inputs)

pred_shape=predictions.get_shape()

#flat=Flatten()(predictions)

out = Flatten()(predictions)


x= Dense(10, activation='softmax',input_shape=pred_shape)(out)

model = Model(input=inputs, output=x)


test_generator = SequenceGenerator(val_file, val_sources,nt,sequence_start_mode='unique', dim_ordering=dim_ordering)
~~~~

Error Info 
~~~~
usr/lib/python2.7/site-packages/keras/initializations.py:65: RuntimeWarning: invalid value encountered in sqrt
  s = np.sqrt(6. / (fan_in + fan_out))
Traceback (most recent call last):
  File "test.py", line 86, in <module>
    x= Dense(10, activation='softmax',input_shape=pred_shape)(out)
  File "/usr/lib/python2.7/site-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/usr/lib/python2.7/site-packages/keras/layers/core.py", line 797, in build
    constraint=self.W_constraint)
  File "/usr/lib/python2.7/site-packages/keras/engine/topology.py", line 418, in add_weight
    weight = initializer(shape, name=name)
  File "/usr/lib/python2.7/site-packages/keras/initializations.py", line 66, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/usr/lib/python2.7/site-packages/keras/initializations.py", line 33, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/usr/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 622, in random_uniform_variable
    low, high, dtype=tf_dtype, seed=seed)(shape)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 171, in _initializer
    return random_ops.random_uniform(shape, minval, maxval, dtype, seed=seed)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 245, in random_uniform
    seed2=seed2)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 220, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 660, in _call_cpp_shape_fn_impl
    s = tensor_util.constant_value_as_shape(op.inputs[idx])
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 742, in constant_value_as_shape
    [d if d != -1 else None for d in value]))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 457, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 378, in as_dimension
    return Dimension(value)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 38, in __init__
    raise ValueError("Dimension %d must be >= 0" % self._value)
ValueError: Dimension -614400 must be >= 0
~~~~
Many thanks

**Comment by bill-lotter** [comment]
Hi I just pushed a commit that I think should fix that.  Let me know if it doesn't and thanks for reporting the issue.

**Comment by wjw1993** [comment]
@bill-lotter  Thank you so much, the problem has been fixed.
