### ISSUE TITLE
kitti_train.py throws error

### ISSUE THREAD

**Issue by ahmadsj94** [coxlab/prednet#34]
> wireless@wireless-Precision-7510:~/git-clones/prednet$ python kitti_train.py 
Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:1255: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:1272: calling reduce_prod (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:1357: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2017-12-05 15:56:18.571703: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-12-05 15:56:18.572021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1062] Found device 0 with properties: 
name: Quadro M2000M major: 5 minor: 0 memoryClockRate(GHz): 1.137
pciBusID: 0000:01:00.0
totalMemory: 3.94GiB freeMemory: 3.29GiB
2017-12-05 15:56:18.572033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1152] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Quadro M2000M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Epoch 1/150
Traceback (most recent call last):
  File "kitti_train.py", line 76, in <module>
    validation_data=val_generator, validation_steps=N_seq_val / batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 560, in get
    six.raise_from(StopIteration(e), e)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
StopIteration

This is the output of running kitti_train.py, unmodified. I'm using Tensorflow 1.4.0, Keras 2.1.2 on a Quadro M2000M. Has anyone else seen this error?

**Comment by ahmadsj94** [comment]
> wireless@wireless-Precision-7510:~/git-clones/prednet$ python kitti_train.py 
Using Theano backend.
WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
Epoch 1/150
Traceback (most recent call last):
  File "kitti_train.py", line 76, in <module>
    validation_data=val_generator, validation_steps=N_seq_val / batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 560, in get
    six.raise_from(StopIteration(e), e)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
StopIteration

Using a Theano backend in Keras throws the same error. I'm using Python2.7, Keras examples like mnist_cnn.py and imdb_cnn_lstm.py work perfectly.

**Comment by ahmadsj94** [comment]
Error did not occur upon reverting to Keras 2.0.8. Will update on further progress.

**Comment by ahmadsj94** [comment]
So it's been working, but the predictions are messed up. The images are heavily hued.

![image](https://user-images.githubusercontent.com/25494818/34323351-962a4ad8-e813-11e7-9398-153139f8a5a0.png)

Has anyone else seen this? I'm using Tensorflow backend with Keras 2.0.6, with CUDNN.

**Comment by riskeverything** [comment]
I get the same question.How did you resolve it？

**Comment by ahmadsj94** [comment]
I haven't resolved it yet. Hoping that the creator will respond. I've examined the code and the images seem fine when they go into the neural net from SequenceGenerator, it's the predictions that seem to be biased towards certain channels. Which channel depends on the numpy random seed.

It works fine for one channel, so you can use it for grayscale.

**Comment by bill-lotter** [comment]
Hi, I think I found the issue.  In Keras 2, there is a bug that when you use TimeDistributed, it overrides the initial weights of the layer to be wrapped and initializes to random weights (this didn't happen in Keras 1). In our case, this results in a meaningless loss function. I made an adjustment for it in the latest commit (9f6482). Give this a shot and let me know if there are still issues - thanks!

**Comment by ahmadsj94** [comment]
@bill-lotter Thanks! The prediction seems to work fine now.

**Comment by riskeverything** [comment]
Unfortunately，it doesn't work for me.It has the same question.
Epoch 1/150
Traceback (most recent call last):
  File "kitti_train.py", line 76, in <module>
    validation_data=val_generator, validation_steps=N_seq_val / batch_size)
  File "/home/robot/Software/anaconda3/envs/py27/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/robot/Software/anaconda3/envs/py27/lib/python2.7/site-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/home/robot/Software/anaconda3/envs/py27/lib/python2.7/site-packages/keras/utils/data_utils.py", line 557, in get
    six.raise_from(StopIteration(e), e)
  File "/home/robot/Software/anaconda3/envs/py27/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
StopIteration
My env is Keras:2.1.2,Tensorflow-gpu:1.3.0,python2.7,GTX1070.

**Comment by ahmadsj94** [comment]
@riskeverything Try reverting to keras 2.0.x. That fixed the stopiteration error for me.

**Comment by riskeverything** [comment]
OK，It works.Thanks a lot : )

**Comment by zcrwind** [comment]
Unfortunately，I also encountered a similar `StopIteration` error as follows:
```
Using TensorFlow backend.
Epoch 1/150
Traceback (most recent call last):
  File "kitti_train.py", line 76, in <module>
    validation_data=val_generator, validation_steps=N_seq_val / batch_size)
  File "/home/zcrwind/.conda/envs/condapython2.7/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/zcrwind/.conda/envs/condapython2.7/lib/python2.7/site-packages/keras/engine/training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
  File "/home/zcrwind/.conda/envs/condapython2.7/lib/python2.7/site-packages/keras/utils/data_utils.py", line 518, in get
    raise StopIteration(e)
StopIteration
```

my keras is 2.0.9, use tensorflow-gpu 1.4, python2.7
Thansk for helping.

**Comment by yushuinanrong** [comment]
Indeed, reverting Keras to 2.0.8 solves the problem.
