### ISSUE TITLE
AttributeError: 'PredNet' object has no attribute 'units'

### ISSUE THREAD

**Issue by Khatwani13** [coxlab/prednet#40]
Hi,
I'm using python=2.7, tensorflow=1.5.0, keras=2.0.2 and I'm facing issue with prednet_train.py

```
Traceback (most recent call last):
  File "train.py", line 59, in <module>
    errors = prednet(inputs)    # (?, nt, nb_layers)
  File "/home/ubuntu/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/keras/layers/recurrent.py", line 252, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/home/ubuntu/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/keras/engine/topology.py", line 554, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/ubuntu/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/keras/layers/recurrent.py", line 269, in call
    initial_states = self.get_initial_states(inputs)
  File "/home/ubuntu/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/keras/layers/recurrent.py", line 218, in get_initial_states
    initial_state = K.tile(initial_state, [1, self.units])  # (samples, output_dim)
AttributeError: 'PredNet' object has no attribute 'units'
```

**Comment by amayuelas** [comment]
I'm facing the same issue. How did you solve it?

**Comment by edwardmfho** [comment]
I faced similar issue as well. Were you able to resolve this issue?
