### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by elesun2018** [coxlab/prednet#50]
coxlab_prednet$ python kitti_train.py 

Using TensorFlow backend.
2019-01-15 16:22:57.611344: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
/usr/local/lib/python2.7/dist-packages/hickle/hickle.py:518: UserWarning: Hickle file appears to be old version (v2), attempting legacy loading...
  warnings.warn("Hickle file appears to be old version (v2), attempting "
Epoch 1/150
Traceback (most recent call last):
  File "kitti_train.py", line 76, in <module>
    validation_data=val_generator, validation_steps=N_seq_val / batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 601, in get
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
NotImplementedError
Exception TypeError: "'NoneType' object is not callable" in <Finalize object, dead> ignored
Exception TypeError: "'NoneType' object is not callable" in <Finalize object, dead> ignored

**Comment by bill-lotter** [comment]
Thanks, this should be fixed now with the latest commit
