### ISSUE TITLE
FailedPreconditionError:  Error while reading resource variable _AnonymousVar459 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/_AnonymousVar459/class tensorflow::Var does not exist.

### ISSUE THREAD

**Issue by Mikkil** [coxlab/prednet#76]
I'm facing the following error whenever I run the kitti_train.py. I am running it on a Windows system with tensorflow version of 2.0.0 and keras version of 2.3.1 and i've a GPU.

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_3 (InputLayer)         (None, 10, 128, 160, 3)   0         
_________________________________________________________________
pred_net_3 (PredNet)         (None, 10, 4)             6915948   
_________________________________________________________________
time_distributed_3 (TimeDist (None, 10, 1)             5         
_________________________________________________________________
flatten_3 (Flatten)          (None, 10)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 11        
=================================================================
Total params: 6,915,964
Trainable params: 6,915,948
Non-trainable params: 16
_________________________________________________________________
None
Epoch 1/150
Traceback (most recent call last):

  File "..\prednet-master\kitti_train.py", line 80, in <module>
    history = model.fit_generator(train_generator,samples_per_epoch / batch_size, nb_epoch, verbose=1, callbacks=callbacks,validation_data=val_generator,validation_steps=N_seq_val / batch_size)

  File "..\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "..\Anaconda3\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)

  File "..\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)

  File "..\Anaconda3\lib\site-packages\keras\engine\training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)

  File "..\Anaconda3\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3740, in __call__
    outputs = self._graph_fn(*converted_inputs)

  File "..\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)

  File "..\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)

  File "..\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)

  File "..\Anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 511, in call
    ctx=ctx)

  File "..\Anaconda3\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

FailedPreconditionError:  Error while reading resource variable _AnonymousVar459 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/_AnonymousVar459/class tensorflow::Var does not exist.
	 [[node pred_net_3/MatMul_3/ReadVariableOp (defined at ..\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference_keras_scratch_graph_36245]

Function call stack:
keras_scratch_graph

**Comment by tfzee** [comment]
I tried it myself it seems it doesnt work with the newer tensorflow/keras versions
