### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by qianwangthu** [coxlab/prednet#9]
I'm using keras 1.1.0 and theano 0.8.2

The error information is:

> Traceback (most recent call last):
  File "kitti_train.py", line 59, in <module>
    errors_by_time = TimeDistributed(Dense(1, weights=[layer_loss_weights, np.zeros(1)], trainable=False), trainable=False)(errors)  # calculate weighted error by layer
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 543, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/wrappers.py", line 98, in build
    self.layer.build(child_input_shape)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 763, in build
    self.set_weights(self.initial_weights)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 966, in set_weights
    str(weights)[:50] + '...')
ValueError: You called `set_weights(weights)` on layer "dense_1" with a  weight list of length 2, but the layer was expecting 0 weights. Provided weights: [array([[ 1.],
       [ 0.],
       [ 0.],
       ...

**Comment by bill-lotter** [comment]
Hmm not sure why that would cause an error in keras 1.1.0.  Have you tried with keras 1.0.7?

**Comment by qianwangthu** [comment]
Sorry I found my version is actually 1.2.0 and somebody are facing the same problem in other projects, they told me rolling back the keras might work and I'm trying.

**Comment by qianwangthu** [comment]
It seems working! THX!

**Comment by bill-lotter** [comment]
Okay cool!
